web:
  #image: marcosfparreiras/ubuntu-rvm-mysql-redis
  image: ditodev/ubuntu-mysql
  links:
   #-  redis6379
   #-  redis6380
   #-  redis6381
    - db
  command: /bin/bash
db:
  image: mysql:5.6.28

  environment:
  - MYSQL_ALLOW_EMPTY_PASSWORD=true

#redis6379:
#  image: redis:2.8.23
#
#redis6380:
#  image: redis:2.8.23
#
#redis6381:
#  image: redis:2.8.23

